default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: postgres
  password: 8732328

development:
  <<: *default
  database: task_manager_development

test:
  <<: *default
  database: task_manager_test

production:
  <<: *default
  database: task_manager_production