default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: task_manager_development
  host: localhost
  port: 5432
  username: postgres
  password: 8732328

test:
  <<: *default
  database: task_manager_test
  host: localhost
  port: 5432
  username: postgres
  password: 8732328

# PRODUCCIÃ“N - USA VARIABLES DE ENTORNO
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>